### ISSUE TITLE
关于全局变量global

### ISSUE THREAD

**Issue by JaffarL** [FE-star/exercise4#29]
试了半天全局变量global。。有个地方不太舒服，感觉怪怪的，代码如下：
function test() {
  this.ttt = "11";
}
function test2(){
	console.log(this.ttt)   //11
	this.ttt = "22";
}
console.log(global.ttt)    //undefined
let ttt = "33";
console.log(global.ttt)    //undefined
test();
console.log(global.ttt);   //11
test2();
console.log(global.ttt);   //22
第一个undefined好理解，第二个，我不是已经赋值了全局变量ttt了么，为何还是输出未定义
全局下的后两个console.log也好理解，但是如果函数内部的这个变量都挂在全局global上了，这不是造成变量污染了么？就像代码中的样子test2中的console.log
求解

**Comment by ceerqingting** [comment]
第一个问题，贴上阮一峰大神的解释：
<img width="605" alt="global" src="https://user-images.githubusercontent.com/20520365/35688709-bdbe9bb8-07ac-11e8-89ac-01bb116005ee.png">

**Comment by JaffarL** [comment]
试一试 用var定义的变量a 用global.a输出依然是undefined
这个问题还是没解决。。阮一峰貌似错了
难道是node版本问题?

**Comment by ceerqingting** [comment]
我node版本8.9.3，试了一下是可以的啊，不是undefined, 你是用的什么版本的？

**Comment by JaffarL** [comment]
我原来是8.7.0
升级到9.4.0
都是undefined

**Comment by miniflycn** [comment]
这种讨论放到  FE-star/2018.1  这个仓库，否则大家都看不到呀
